### ISSUE TITLE
Elasticsearch requires authentication/authorization to perform requests

### ISSUE THREAD

**Issue by rajbirjohar** [samuelgja/elastic-tiny-client#1]
So I came across your library by accident and thankfully it all works as intended for my use case but I kept hitting the Elasticsearch error stating that it's missing some sort of authorization even though I put in the API key that is generated from their API.

It only worked with directly putting in a username/password combination as part of the config object. This is strange though because the Elasticsearch URL that I am using already contains the username and password as part of the URL <username>:<password>. 

Do you think this could be due to Elasticsearch directly or the package?

**Comment by samuelgja** [comment]
Can you send your code what you are trying to do? I think some parts of authorizations can be missed in this package. But maybe its issue on elastic itself.

**Comment by samuelgja** [comment]
Did you use it like this:

```ts
    const client = new ElasticClient({
      hosts: ['http://localhost:9200'],
      authorization: { password: 'yourElasticPassword', username: 'elastic' },
    })
```

**Comment by rajbirjohar** [comment]
```ts
const client = new ElasticClient({
    hosts: [ELASTICSEARCH_URL],
    authorization: {
      username: ELASTICSEARCH_USERNAME,
      password: ELASTICSEARCH_PASSWORD,
    },
  });
```

Yep. It would be cool to support urls with credentials within it like so:

```ts
const client = new ElasticClient({
    hosts: https://<user>:<password>@<company>.io,
  });
```

**Comment by samuelgja** [comment]
I added support for it here: https://github.com/samuelgja/elastic-tiny-client/pull/2

**Comment by rajbirjohar** [comment]
Thanks!
